[workspace]

# We will tell cargo to look for our projects
# inside a clean "levels" folder
members = [
    "levels/yotquitas-node",
]

# Optional: This tells all sub-projects to use the same
# "target" (build) directory, which is much cleaner.
[profile.release]
lto = true
codegen-units = 1